# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 450)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Undo = QtWidgets.QPushButton(self.centralwidget)
        self.Undo.setGeometry(QtCore.QRect(100, 350, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Undo.setFont(font)
        self.Undo.setStyleSheet("border: 5px solid #6b0071;\n"
"border-radius: 10px;\n"
"color: white;")
        self.Undo.setObjectName("Undo")
        self.Pause = QtWidgets.QPushButton(self.centralwidget)
        self.Pause.setGeometry(QtCore.QRect(190, 342, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Pause.setFont(font)
        self.Pause.setStyleSheet("border: 5px solid #6b0071;\n"
"border-radius: 10px;\n"
"color: white;")
        self.Pause.setObjectName("Pause")
        self.Scip = QtWidgets.QPushButton(self.centralwidget)
        self.Scip.setGeometry(QtCore.QRect(280, 350, 75, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.Scip.setFont(font)
        self.Scip.setStyleSheet("border: 5px solid #6b0071;\n"
"border-radius: 10px;\n"
"color: white;")
        self.Scip.setObjectName("Scip")
        self.Load = QtWidgets.QPushButton(self.centralwidget)
        self.Load.setGeometry(QtCore.QRect(670, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Load.setFont(font)
        self.Load.setStyleSheet("border: 5px solid #6b0071;\n"
"border-radius: 10px;\n"
"color: white;")
        self.Load.setObjectName("Load")
        self.Music = QtWidgets.QLabel(self.centralwidget)
        self.Music.setGeometry(QtCore.QRect(70, 10, 511, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Music.setFont(font)
        self.Music.setStyleSheet("border-bottom: 5px solid #6b0071;\n"
"border-radius: 0px;\n"
"color: white;")
        self.Music.setObjectName("Music")
        self.listMusic = QtWidgets.QListWidget(self.centralwidget)
        self.listMusic.setGeometry(QtCore.QRect(490, 90, 291, 341))
        self.listMusic.setObjectName("listMusic")
        self.Play = QtWidgets.QPushButton(self.centralwidget)
        self.Play.setGeometry(QtCore.QRect(190, 382, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Play.setFont(font)
        self.Play.setStyleSheet("border: 5px solid #6b0071;\n"
"border-radius: 10px;\n"
"color: white;")
        self.Play.setObjectName("Play")
        self.Eternety = QtWidgets.QRadioButton(self.centralwidget)
        self.Eternety.setGeometry(QtCore.QRect(280, 410, 82, 21))
        self.Eternety.setStyleSheet("border: 5px solid #6b0071;\n"
"border-radius: 10px;\n"
"color: white;")
        self.Eternety.setObjectName("Eternety")
        self.Icon = QtWidgets.QLabel(self.centralwidget)
        self.Icon.setGeometry(QtCore.QRect(86, 52, 291, 251))
        self.Icon.setText("")
        self.Icon.setObjectName("Icon")
        self.MusicTime = QtWidgets.QSlider(self.centralwidget)
        self.MusicTime.setGeometry(QtCore.QRect(150, 290, 160, 22))
        self.MusicTime.setMaximum(0)
        self.MusicTime.setOrientation(QtCore.Qt.Horizontal)
        self.MusicTime.setObjectName("MusicTime")
        self.MaxTime = QtWidgets.QLabel(self.centralwidget)
        self.MaxTime.setGeometry(QtCore.QRect(320, 290, 41, 21))
        self.MaxTime.setStyleSheet("border-bottom: 5px solid #6b0071;\n"
"border-radius: 0px;\n"
"color: white;")
        self.MaxTime.setAlignment(QtCore.Qt.AlignCenter)
        self.MaxTime.setObjectName("MaxTime")
        self.PresentTime = QtWidgets.QLabel(self.centralwidget)
        self.PresentTime.setGeometry(QtCore.QRect(90, 290, 41, 21))
        self.PresentTime.setStyleSheet("border-bottom: 5px solid #6b0071;\n"
"border-radius: 0px;\n"
"color: white;")
        self.PresentTime.setAlignment(QtCore.Qt.AlignCenter)
        self.PresentTime.setObjectName("PresentTime")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 451))
        self.label.setStyleSheet("background-color: #232323;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.Undo.raise_()
        self.Pause.raise_()
        self.Scip.raise_()
        self.Load.raise_()
        self.Music.raise_()
        self.listMusic.raise_()
        self.Play.raise_()
        self.Eternety.raise_()
        self.Icon.raise_()
        self.MusicTime.raise_()
        self.MaxTime.raise_()
        self.PresentTime.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Undo.setText(_translate("MainWindow", "<"))
        self.Pause.setText(_translate("MainWindow", "Play"))
        self.Scip.setText(_translate("MainWindow", " >"))
        self.Load.setText(_translate("MainWindow", "Load"))
        self.Music.setText(_translate("MainWindow", "Music"))
        self.Play.setText(_translate("MainWindow", "Stop"))
        self.Eternety.setText(_translate("MainWindow", "Eternety"))
        self.MaxTime.setText(_translate("MainWindow", "1:02"))
        self.PresentTime.setText(_translate("MainWindow", "0"))
